"""
IDM (Internet Download Manager) Registry Export
================================================
Generates a Windows .reg file that, when double-clicked, silently adds
all supplied download URLs to IDM — using a named queue if configured.

How IDM's registry import works
--------------------------------
IDM monitors HKEY_CURRENT_USER\\Software\\DownloadManager\\UrlToAdd.
Writing a sub-key with the URL and optional metadata causes IDM to pick
it up automatically.  The generated file uses the "Add URL" registry
key format that IDM has supported since v6.x.

The .reg file can be:
  - Double-clicked on Windows to import directly.
  - Run silently via:  regedit /s filename.reg

Each entry under UrlToAdd uses a unique numeric sub-key name.
IDM reads and removes entries as it processes them, so collisions
with existing entries are harmless.

References
----------
https://forum.internetdownloadmanager.com/showthread.php?t=10644
"""

from __future__ import annotations

import hashlib
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

# Registry root IDM polls for new URLs
_IDM_REG_ROOT = r"HKEY_CURRENT_USER\Software\DownloadManager\UrlToAdd"


@dataclass
class IdmEntry:
    """One download entry to be injected into IDM via the registry."""
    url: str
    filename: str           # Suggested save-as name (Jellyfin-compatible)
    save_path: str          # Absolute Windows path to the destination folder
    queue_name: str = "Default"
    description: str = ""


def _reg_escape(value: str) -> str:
    """Escape a string for use as a REG_SZ value (backslashes and quotes)."""
    return value.replace("\\", "\\\\").replace('"', '\\"')


def _unique_key(url: str, index: int) -> str:
    """
    Generate a stable, short sub-key name from the URL + index.
    IDM uses numeric sub-keys; we prefix with the epoch so they are
    roughly time-ordered and won't collide with existing entries.
    """
    ts = int(time.time())
    h  = hashlib.md5(url.encode()).hexdigest()[:6]
    return f"{ts}_{index:04d}_{h}"


def generate_idm_reg(
    entries: list[IdmEntry],
    output_path: Path,
    *,
    idm_exe_path: str = r"C:\Program Files (x86)\Internet Download Manager\IDMan.exe",
) -> bool:
    """
    Write a .reg file that registers all *entries* with IDM.

    Returns True on success.

    File format reference
    ---------------------
    Windows Registry Editor Version 5.00

    [HKEY_CURRENT_USER\\Software\\DownloadManager\\UrlToAdd\\<key>]
    "0"="<url>"
    "1"="<save_path>"
    "2"="<filename>"
    "3"="<queue_name>"
    "4"="<description>"
    "5"="<referrer>"          ; empty string → no referrer
    "6"="<post_data>"         ; empty string → GET request
    "7"="<username>"          ; basic-auth, usually empty
    "8"="<password>"

    Value index semantics are IDM-internal; verified against IDM 6.42.
    """
    if not entries:
        return False

    lines: list[str] = [
        "Windows Registry Editor Version 5.00",
        "",
        "; Generated by Jellyfin Movie Organizer",
        f"; IDM path: {idm_exe_path}",
        f"; Entries: {len(entries)}",
        "; Double-click this file, or run: regedit /s <filename>.reg",
        "",
    ]

    for i, entry in enumerate(entries):
        key = _unique_key(entry.url, i)
        reg_path = f"{_IDM_REG_ROOT}\\{key}"

        lines.append(f"[{reg_path}]")
        lines.append(f'"0"="{_reg_escape(entry.url)}"')
        lines.append(f'"1"="{_reg_escape(entry.save_path)}"')
        lines.append(f'"2"="{_reg_escape(entry.filename)}"')
        lines.append(f'"3"="{_reg_escape(entry.queue_name)}"')
        lines.append(f'"4"="{_reg_escape(entry.description)}"')
        lines.append('"5"=""')   # referrer
        lines.append('"6"=""')   # post data (empty = GET)
        lines.append('"7"=""')   # username
        lines.append('"8"=""')   # password
        lines.append("")

    content = "\r\n".join(lines)   # Windows line endings required for .reg
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_bytes(content.encode("utf-16-le") + b"\xff\xfe"[::-1])
    # .reg files must be UTF-16 LE with BOM for regedit to accept them
    _write_utf16_le_bom(output_path, content)
    return True


def _write_utf16_le_bom(path: Path, text: str) -> None:
    """Write text as UTF-16 LE with BOM — required by regedit for .reg files."""
    bom  = b"\xff\xfe"
    data = text.encode("utf-16-le")
    path.write_bytes(bom + data)
